sudo: false
language: node_js
notifications:
  email:
  - hust2012jiangkai@gmail.com
node_js:
- 9
script:
- npm run lint
deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: C5+sdDxgoygCdmvb/NMrZAFwLupD3kxKx6gBavtX4AKbfii2GATjHARSz+XrMW2yOCkjVQdKnwxw+7YfZAqHpOE0Lh9JJOMWii0DGVoYeyzj8cmO8uzJkranEhRvN+/iTVPNs4E3+C94pDR1ZN7cq6IKczD8VjvuPdWpEHxFamhTv162XFekuWJmwV8Uclhet8iAK2fzOD+ZhC4S8ISqdghLfYpAaoiGcT11qUH3s5KtK5Re/dVcXlnWv3SEaEkasO5rFZ/R33xaQUb4pDP5Tb6m4/Cnf5uO97tuhnG2OT7zUDdI3hKKRGuc1Ah12+dAY20hvTaoujigDbwP1EnWMEGNOtvWAy3CUOv6f7xdrgHQGMljxr2a5DtyRC7LdAxC0ijMi1ivG/kgnkOUpXW0cNNbvHSzklKDle+a1nYsWl/RbCvmhbD0uSFcUyLi10zzpVkkzzh7jFura4KiaL3uMmGhubOybfWzI4u3ROasegCAEjxWZaTP6KwOS3cfMEHOQHROPy8iCV6ysWyo6a55T91AsQyf0sl2totCINRwHmOVZw5jq45VtvJfjgA2fpTqy/+7u4VzNlrz/MnBFmr/xc9NzrxDlmG57l9CpUyUfvaDqV11DHZlrbfuoQpRCEvuORDFo2JDifvkHYugCFUsXK/vILomKH2jrXvtgvaChyg=
  app: ant-bot
  on:
    repo: ant-design/ant-bot
